// pages/flutter/index.vue
<template>
  <section class="mx-auto max-w-6xl px-6 xl:px-0">
    <div class="h-4"></div>
    <!-- <adsbygoogle
      ad-slot="5508803088"
      ad-format="auto"
      ad-label="flutter-ads"
    />
    <div class="h-4"></div> -->
    <iframe data-aa='2152646' src='//acceptable.a-ads.com/2152646' style='border:0px; padding:0; width:100%; height:100%; overflow:hidden; background-color: transparent;'></iframe>
    <div class="h-4"></div>
    <div class="flex">
      <div class="w-full border border-gray-100 rounded-xl p-6 ">
        <p class="mb-4 text-lg font-medium">Search in 100+ Flutter Examples </p>
        <div class="h-4"></div>
        <input type="text" v-model="input" placeholder="search eg. day 22, GetX, Login" class="border border-gray-200 focus:border-blue-600 focus:shadow-md outline-none text-gray-600 text-md py-3 px-4 rounded-lg w-full bg-gray-100">
      </div>
    </div>
    <div class="h-4"></div>
    <div class="grid grid-cols-1 md:grid-cols-2 pt-8 gap-10" v-if="days && days.length">
      <div v-for="(day, index) in days" :key="index" class="bg-white rounded-xl border-2 border-gray-100">
        <div class="">
          <iframe class="rounded-t-xl" width="100%" height="400" :src="day.video.replace('youtu.be', 'youtube.com/embed')" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <div class="p-4 pr-2">
            <h3 class="mt-4 font-medium text-gray-700">{{ day.name }}</h3>
            <p class="text-gray-400 tracking-wider text-xs mt-2">{{ day.summery }}</p>
            <div class="mt-5 text-right">
              <a :href="day.repository" title="" class="hover:bg-gray-100 px-4 py-2 rounded-full"> 🔗 Source code</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div v-else>
      <div class="text-center mt-10">
        <h1 class="text-xl font-bold tracking-wide">No Flutter Examples Found</h1>
        <p class="text-gray-600 text-lg mt-4">
          Please try another search
        </p>
      </div>
    </div>
    <div class="h-40"></div>
  </section>
</template>

<script>
export default {
  async asyncData({ $content }) {
    let days = await $content('flutter').fetch()
    days = days[0].data.reverse()

    return { days }
  },

  data() {
    return {
      timeout: null,
      searchKey: '',
      days: [],
      originalDays: [],
    }
  },

  mounted() {
    this.originalDays = this.days
  },

  computed: {
    input: {
      get() {
        return this.searchKey
      },
      set(value) {
        if (this.timeout) clearTimeout(this.timeout)
        this.timeout = setTimeout(() => {
          this.search(value)
        }, 500)
      }
    }
  },

  methods: {
    search(value) {
      this.searchKey = value

      if (value.length > 0) {
        this.days = this.originalDays.filter(day => {
          return day.name.toLowerCase().includes(value.toLowerCase())
        })
      } else {
        this.days = this.originalDays
      }
    },

    breadcrumbLinks() {
      return [
        {
          title: 'Home',
          to: '/'
        },
        {
          title: 'Flutter',
          to: '/flutter'
        }
      ]
    }
  },

  head: {
    title: 'Flutter 100 Days of Code UI Design Example - afgprogrammer',
    meta: [
      {
        name: 'author',
        content: 'Mohammad Rahmani - afgprogrammer'
      },
      {
        name: 'description',
        content: 'Hey there! I\'m Mohammad Rahmani, a Flutter developer based in Kabul. I love Flutter, and I\'m always looking for new challenges. In this page you can find my 100 days of Flutter journey.',
      },
      {
        key: 'og:title',
        property: 'og:title',
        content: 'Everyday Flutter UI Design Example - afgprogrammer',
      },
      {
        key: 'og:description',
        property: 'og:description',
        content: 'Hey there! I\'m Mohammad Rahmani, a Flutter developer based in Kabul. I love Flutter, and I\'m always looking for new challenges. In this page you can find my 100 days of Flutter journey.',
      },
      {
        key: 'og:url',
        property: 'og:url',
        content: 'https://afgprogrammer.com/flutter',
      },
      {
        key: 'twitter:title',
        name: 'twitter:title',
        content: 'Everyday Flutter UI Design Example - afgprogrammer',
      },
      {
        key: 'twitter:card',
        name: 'twitter:card',
        content: 'summary',
      },
      {
        key: 'twitter:creator',
        name: 'twitter:creator',
        content: '@afgprogrammer',
      },
      {
        key: 'twitter:description',
        name: 'twitter:description',
        content: 'Hey there! I\'m Mohammad Rahmani, a Flutter developer based in Kabul. I love Flutter, and I\'m always looking for new challenges. In this page you can find my 100 days of Flutter journey.',
      }
    ]
  }
}
</script>

// src/app/flutter/page.tsx
"use client";

import {
  Box,
  Button,
  Card,
  CardSection,
  Container,
  Grid,
  GridCol,
  Group,
  Space,
  Text,
  TextInput,
  Title,
} from "@mantine/core";
import SiteFooter from "@/_components/footer/Footer";
import { IconArrowUpRight, IconLink } from "@tabler/icons-react";
import Days from "@/data/100days.json";
import { useEffect, useState } from "react";
import { useDebouncedCallback } from "@mantine/hooks";

interface exampleType {
  name: string;
  summery: string;
  repository: string;
  video: string;
  tags: string[];
}

export default function FlutterPage() {
  const [originalData, setOriginalData] = useState<exampleType[]>(
    Days.data.reverse()
  );
  const [search, setSearch] = useState("");
  const [visibleCount, setVisibleCount] = useState(0);
  const [perPage, setPerPage] = useState(9);
  const [examples, setExamples] = useState<exampleType[]>([]);

  useEffect(() => {
    setExamples(originalData.slice(visibleCount, perPage));
    setVisibleCount(perPage);
  }, []);

  const handleSearch = useDebouncedCallback(async (query: string) => {
    if (query.length) {
      let data = originalData.filter((day) => {
        return day.name.toLowerCase().includes(query.toLowerCase());
      });

      setExamples(data);
    } else {
      setExamples(originalData.slice(0, perPage));
    }
  }, 500);

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSearch(event.currentTarget.value);
    handleSearch(event.currentTarget.value);
  };

  const loadMore = () => {
    setExamples((prev) => [
      ...prev,
      ...originalData.slice(visibleCount, visibleCount + perPage),
    ]);
    setVisibleCount(visibleCount + perPage);
  };

  return (
    <>
      <Container size="xl" pos="relative">
        <Box
          px={32}
          py={58}
          mt={40}
          style={{
            overflow: "hidden",
            position: "relative",
            borderRadius: 16,
            background:
              "light-dark(var(--mantine-color-gray-2), var(--mantine-color-dark-6))",
          }}
        >
          <Title
            order={1}
            fz={36}
            fw={600}
            ta="center"
            c={"light-dark(var(--mantine-color-dark-9), white)"}
          >
            Discover the Most Trending Flutter UI Designs
          </Title>
          <Text ta="center" mt={16} c="gray">
            Search in 100+ flutter UI design examples
          </Text>
          <Space h={40} />
          <Container size="sm">
            <TextInput
              radius="xl"
              size="lg"
              fz={14}
              placeholder="Search e.g e-commerce, login, state management, day 28"
              value={search}
              onChange={handleChange}
            />
          </Container>
        </Box>
        <Space h={40} />
        <Grid>
          {examples.map((day, i) => {
            return (
              <GridCol key={`id-${i}`} span={{ lg: 4, sm: 6, xs: 12 }}>
                <Card radius="md" withBorder style={{ overflow: "hidden" }}>
                  <CardSection>
                    <Box>
                      <iframe
                        width="100%"
                        height="300"
                        src={day.video.replace("youtu.be", "youtube.com/embed")}
                        title="YouTube video player"
                        frameBorder={0}
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                      ></iframe>
                    </Box>
                  </CardSection>
                  <Text fw={600} mt={16} fz={14} c="light-dark(black, white)">
                    {day.name}
                  </Text>
                  <Text mt={8} c="gray" fz={13} truncate>
                    {day.summery}
                  </Text>

                  <Button
                    variant="light"
                    radius="xl"
                    mt={32}
                    leftSection={<IconLink size={18} />}
                    component="a"
                    href={day.repository}
                    target="_blank"
                  >
                    source code
                  </Button>
                </Card>
              </GridCol>
            );
          })}
        </Grid>
        <Space h={80} />
        {examples.length && !search.length ? (
          <Group justify="center">
            <Button
              w={200}
              size="lg"
              fz={14}
              variant="default"
              radius="xl"
              onClick={() => loadMore()}
            >
              Load More
            </Button>
          </Group>
        ) : null}
      </Container>
      <Space h={150} />
      <SiteFooter />
    </>
  );
}
